[package]
name = "edbrute"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
ed25519-dalek = "1.0.1"
hex = "0.4.3"
indicatif = "0.17.3"
num_cpus = "1.15.0"
rand = "0.7.0"
