[package]
name = "edbrute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.1"
hex = "0.4.3"
num_cpus = "1.15.0"
rand = "0.7.0"
